### ISSUE TITLE
raacan build

### ISSUE THREAD

**Issue by BevoSteve** [shincoder/harmless-migration#2]
Hello, just wondering If you created raacan.com? any chance you'll be able to upload here.

**Comment by jaouadk** [comment]
Hey Steve, thanks for getting in touch. 

Yes I'm the creator of Raacan. 

It's not intended to be distributed for free though.

**Comment by BevoSteve** [comment]
where are you selling it now funnelflux.com?

I never seen your site go live since your beta.

**Comment by jaouadk** [comment]
No funnelflux is another software that I don't own.

After a failed deal with a company trying to buy the beta version. I switched the model from self hosted to SAAS.

Currently under development.

**Comment by BevoSteve** [comment]
what's your skype/email?, friend wants to get in touch with you.

**Comment by jaouadk** [comment]
You can contact me at jaouad.elmoussaoui@gmail.com
